// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "6daf41f5-eda0-4bf3-8de0-c60f12d999e4";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onRegSSID1Change();
void onRegSSID1PassChange();
void onButton03Change();
void onTestSwitchChange();

String regSSID1;
String regSSID1_pass;
bool button_03;
bool test_switch;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(regSSID1, READWRITE, ON_CHANGE, onRegSSID1Change);
  ArduinoCloud.addProperty(regSSID1_pass, READWRITE, ON_CHANGE, onRegSSID1PassChange);
  ArduinoCloud.addProperty(button_03, READWRITE, ON_CHANGE, onButton03Change);
  ArduinoCloud.addProperty(test_switch, READWRITE, ON_CHANGE, onTestSwitchChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
